//
//
//

var MEDLEY = MEDLEY || {};

//
//  fab related
//
MEDLEY.LAYERHEIGHT = 0.2; // mm

//
//  ui related
//
MEDLEY.WIDTHSEARCHBOX = 240;
MEDLEY.NUMSEARCHRESULTSCOLS = 2;
MEDLEY.PADDINGSEARCHRESULTS = 16;
MEDLEY.WIDTHSEARCHRESULTITEM = 96;
MEDLEY.PADDINGSEARCHRESULTITEM = 8;