//
//
//

var MEDLEY = MEDLEY || {};

//
//  resource
//
MEDLEY.ASSETDIR = 'assets';
MEDLEY.TEMPLATEDIR = 'assets';
MEDLEY.DIRLIBRARY = 'matobjs.json';

//
//  material related
//
MEDLEY.NUMSTARS = 5;
MEDLEY.HEATCONDUCTIVITY = 'heat conductivity';
MEDLEY.TENSILESTRENGTH = 'tensile strength';
MEDLEY.COMPRESSIONSTRENGTH = 'compression strength';
MEDLEY.SOFTNESS = 'softness';
MEDLEY.FRICTION = 'friction';
MEDLEY.ELASTICITY = 'elasticity';
MEDLEY.SHEARSTRENGTH = 'shear strength';
MEDLEY.ABRASIVERESISTANCE = 'abrasive resistance';
// ...

MEDLEY.MATERIALPROPERTIES = [
    '-',
    MEDLEY.HEATCONDUCTIVITY,
    MEDLEY.TENSILESTRENGTH,
    MEDLEY.COMPRESSIONSTRENGTH,
    MEDLEY.SOFTNESS,
    MEDLEY.FRICTION,
    MEDLEY.ELASTICITY,
    MEDLEY.SHEARSTRENGTH,
    MEDLEY.ABRASIVERESISTANCE
    // ...
];

//
//  fab related
//
MEDLEY.LAYERHEIGHT = 0.2; // mm

//
//  ui related
//

// panel
MEDLEY.WIDTHPANEL = 360;
MEDLEY.PADDINGPANEL = 10;

// search box
MEDLEY.TABLEPANEL = MEDLEY.TEMPLATEDIR + '/panel_table.html';
MEDLEY.WIDTHSEARCHBOX = '90%';
MEDLEY.NUMSEARCHRESULTSCOLS = 1;
MEDLEY.PADDINGSEARCHRESULTS = 8;
MEDLEY.WIDTHSEARCHRESULTITEM = 64;
MEDLEY.PADDINGSEARCHRESULTITEM = 0;
MEDLEY.CODEWHITESTAR = '&#9734;';
MEDLEY.CODEBLACKSTAR = '&#9733;';
MEDLEY.MAXNUMPROPERTIESONCARD = 3;

// material properties dialog
MEDLEY.WIDTHDIALOG = 480;
MEDLEY.HEIGHTDIALOG = 640;
MEDLEY.WIDTHDIALOGTHUMBNAIL = 96;
MEDLEY.TABLEINFODIALOG = MEDLEY.TEMPLATEDIR + '/dialog_table.html';
MEDLEY.CODECROSS = '&#10006;';//'&times;';